language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run build
after_success:
  - npm run semantic-release
branches:
  only:
    - master
